[package]
name = "bitsynth"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
z3 = "0.12.1"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_debug"] }
colog = "1.3.0"

[profile.release]
debug = true