name: CI
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: 
      image: innocentuslime/bitsynth-ci:ubuntu-v1
      options: --user root
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Build
       run: dune build
     - name: Test
       run: dune test
