name: CI
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: innocentuslime/bitsynth-ci:ubuntu-v2
    steps:
     - name: Init env
       run: opam init && eval $(opam env)
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Build
       run: dune build
     - name: Test
       run: dune test
