name: CI
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: innocentuslime/bitsynth-ci:ubuntu-v2
    defaults:
      run:
        shell: bash
    steps:
    - run: |
        echo "/home/opam/.opam/5.1/bin" >> $GITHUB_PATH
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Build
       run: dune build
     - name: Test
       run: dune test
